spring:
  main:
    banner-mode: "off"
  datasource:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      register-mbeans: true
  jpa:
    open-in-view: false
    # Uncomment to print the SQL statements (note that the logs do not integrate with the logging framework)
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.H2Dialect
      # Uncomment to "pretty print" the SQL logs
#      hibernate.format_sql: true
       # Uncomment to prefix the SQL logs with the HQL
#      hibernate.use_sql_comments: true
      # Uncomment to enable the statistics
      hibernate.generate_statistics: true
      # Uncomment to use a custom Hibernate session metrics logger
#      hibernate.session.events.auto: com.adeliosys.sample.CustomSessionEventListener

logging.level:
  com.adeliosys: debug
  # Uncomment to logs the SQL statements
#  org.hibernate.SQL: debug
  # Uncomment to log the parameters of the SQL statements
#  org.hibernate.type.descriptor.sql.BasicBinder: trace
  # Uncomment to log some session stats (this requires the statistics to be enabled)
  org.hibernate.stat: debug
  # Uncomment to disable the default Hibernate session metrics logger
  org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: warn
