spring:
  main:
    banner-mode: "off"
  datasource:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      register-mbeans: true
  jpa:
    open-in-view: false
    # Uncomment to print the SQL statements (note that the logs do not integrate with the logging framework)
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.H2Dialect
      # Uncomment to "pretty print" the SQL logs
#      hibernate.format_sql: true
       # Uncomment to prefix the SQL logs with the HQL
#      hibernate.use_sql_comments: true
      # Uncomment to log the slow queries (but it will not work with H2 since the embedded DB is way too fast)
#      hibernate.session.events.log.LOG_QUERIES_SLOWER_THAN_MS: 1
      # Uncomment to enable the statistics
      hibernate.generate_statistics: true
      # Uncomment to use a custom Hibernate session metrics logger
      hibernate.session.events.auto: org.apache.catalina.startup.Bootstrap
      # Uncomment to publish the session factory metrics through JMX (but this is not supported by Hibernate 6)
#      hibernate.jmx.enabled: true

server:
  port: 8085

logging.level:
  com.adeliosys: debug
  # Uncomment to log the SQL statements
#  org.hibernate.SQL: debug
  # Uncomment to log the parameters of the SQL statements with Hibernate 5
#  org.hibernate.type.descriptor.sql.BasicBinder: trace
  # Uncomment to log the parameters of the SQL statements with Hibernate 6
#  org.hibernate.orm.jdbc.bind: trace
  # Uncomment to log the statement metrics (this requires the statistics to be enabled)
#  org.hibernate.stat: debug
  # Uncomment to disable the default Hibernate session metrics logger
  org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: warn
