spring:
  main:
    banner-mode: "off"
  jpa:
    open-in-view: false
    # Uncomment to print the SQL statements (note that the logs do not integrate with the logging framework)
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.H2Dialect
      # Uncomment to "pretty print" the SQL logs
#      hibernate.format_sql: true
       # Uncomment to prefix the SQL logs with the HQL
#      hibernate.use_sql_comments: true
      # Uncomment to enable the statistics
      hibernate.generate_statistics: true

logging.level:
  com.adeliosys: debug
  # Uncomment to logs the SQL statements
#  org.hibernate.SQL: debug
  # Uncomment to log the parameters of the SQL statements
#  org.hibernate.type.descriptor.sql.BasicBinder: trace
  # Uncomment to log some session stats (this requires the statistics to be enabled)
  org.hibernate.stat: debug
